import type { Assento, Evento, Sessao } from '../types'
import { PaymentActions } from '../components/booking/PaymentActions'
import { SeatMap } from '../components/booking/SeatMap'

type EventDetailsPageProps = { evento: Evento; sessao: Sessao | null; assento: Assento | null; carregando: boolean; onBack: () => void; onSession: (sessao: Sessao) => void; onSeat: (assento: Assento) => void; onPay: (aprovado: boolean) => void }

export function EventDetailsPage({ evento, sessao, assento, carregando, onBack, onSession, onSeat, onPay }: EventDetailsPageProps) {
  return <section><button className="mb-8 text-sm font-medium text-orange-400 transition hover:text-orange-300" onClick={onBack}>← voltar para filmes</button><div className="grid gap-8 lg:grid-cols-[280px_1fr] lg:gap-12">{evento.posterUrl && <img className="mx-auto w-52 rounded-2xl border border-zinc-800 object-cover shadow-2xl shadow-black/30 lg:mx-0 lg:w-full" src={evento.posterUrl} alt={`Pôster de ${evento.titulo}`} />}<div><p className="text-xs font-semibold tracking-[0.24em] text-orange-400">EM CARTAZ</p><h1 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-6xl">{evento.titulo}</h1><p className="mt-5 max-w-2xl leading-7 text-zinc-400">{evento.sinopse || 'Uma experiência cinematográfica para viver na sala.'}</p><h2 className="mt-10 text-xl font-semibold text-white">Escolha uma sessão</h2><div className="mt-4 flex flex-wrap gap-3">{evento.sessoes.map((item) => { const data = new Date(item.dataHora); const selected = sessao?.id === item.id; return <button className={`min-w-44 rounded-xl border p-4 text-left transition ${selected ? 'border-orange-400 bg-orange-400/10' : 'border-zinc-800 bg-zinc-900 hover:border-zinc-600'}`} key={item.id} onClick={() => onSession(item)}><strong className="block text-sm text-white">{data.toLocaleDateString('pt-BR')}</strong><span className="mt-1 block text-sm text-zinc-400">{data.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} · {item.local}</span><b className="mt-3 block text-sm text-orange-400">R$ {Number(item.preco).toFixed(2)}</b></button> })}</div>{sessao && <><SeatMap sessao={sessao} selecionado={assento} onSelect={onSeat} /><PaymentActions sessao={sessao} assento={assento} carregando={carregando} onPay={onPay} /></>}</div></div></section>
}
